### PR TITLE
#37 Use `protected` method scope to make class overwrites easier

### PR DESCRIPTION
**Pull request by cewald**
> While I was overwriting some classes with a module of our own to keep this module "update-able", I noticed that there is by far every function is using the scope private. This makes it not possible to simply extend a class function by another without copying the whole class.
> 
> Is there a specific reason for that?
Otherwise I would suggest to change them to the protectedfunction scope.

See #37

### CODE REVIEW

**Comment by afirlejczyk** [comment]
Hi @cewald could you resolve conflicts ?

**Comment by cewald** [comment]
@afirlejczyk Sorry, didn't looked into this PR and saw the conflict.
It's kind of a harsh PR – do think it causes problems to change the scopes or does your follow a an idea by using privates?

**Comment by afirlejczyk** [comment]
both option has pros and cons, I am not particularly bound to private scope.

It was recommended for coding standard, but I can't remember exactly where I read it..
Probably I was using https://github.com/magento/marketplace-eqp/.
https://github.com/magento/marketplace-eqp/issues/27: "Use of protected class members is discouraged"


I just don't know if we should have 'protected' everywhere  ? maybe we should only use `protected` in variable, methods which really might be overridden and add event in other cases so external modules can listen to them ? 


which classes/methods do you think might be override the most ? Maybe we can dispatch some new events to make it easier to customize ? 

I can also merge PR as it is. :)

**Comment by cewald** [comment]
I'm also not sure about it. I'm coming from Magento 1.9 development and am not using the private scope very much. Mainly because of the modularity of modules, which then overwrites other modules and so on. I also think that it isn't the best idea to just search and replace privates to protected and look instead where a change would be reasonable. But that again seems like a lot of work.

**Comment by afirlejczyk** [comment]
Yes, it might take a minute.
I will take a deeper look into this next week and see which places would be reasonable :)

**Comment by afirlejczyk** [comment]
I checked most of the classes + create new PR for this. 
https://github.com/DivanteLtd/magento1-vsbridge-indexer/pull/43

I will close this PR.

**Pull request closed without merging**
